### ISSUE TITLE
Invite failed as it has not been verified

### ISSUE THREAD

**Issue by airmanparker34** [modio/DiscordBot#13]
When attempting to invite the Mod.IO Discord bot into my Discord server, receive the following error in the attached screenshot.

1) Go into Discord bot invite link on this Gituhb
2) Permissions are both checked
3) Verify if human
4) Fail

![ModIO_Bot_Fail](https://user-images.githubusercontent.com/81290842/222928450-c4debf1c-1e8a-4ae0-a1ac-d185c0c4f6f4.JPG)

**Comment by nickelc** [comment]
I've heard from the modio team, that they had to move the modbot account, which means its re-going through the verification process.

**Comment by intenscia** [comment]
This is now verified and should work, please let us know if not!
